<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.3.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма spares',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U2819' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 8,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'E-mail\' не может быть пустым.',
				'format' => 'Поле \'E-mail\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U2840' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Компания',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Компания\' не может быть пустым.'
			)
		),
		'custom_U3276' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон\' не может быть пустым.'
			)
		),
		'custom_U3288' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Тип машины',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Тип машины\' не может быть пустым.'
			)
		),
		'custom_U3300' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Модель',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Модель\' не может быть пустым.'
			)
		),
		'custom_U3312' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Серийный номер',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Серийный номер\' не может быть пустым.'
			)
		),
		'custom_U3324' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Год и месяц выпуска',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Год и месяц выпуска\' не может быть пустым.'
			)
		),
		'custom_U3336' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Продукт переработки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Продукт переработки\' не может быть пустым.'
			)
		),
		'custom_U3348' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Список запчастей',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Список запчастей\' не может быть пустым.'
			)
		),
		'custom_U3366' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Улица, дом',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Улица, дом\' не может быть пустым.'
			)
		),
		'custom_U3378' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Город',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Город\' не может быть пустым.'
			)
		),
		'custom_U3390' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Область',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Область\' не может быть пустым.'
			)
		),
		'custom_U3402' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Почтовый индекс',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Почтовый индекс\' не может быть пустым.'
			)
		),
		'custom_U3414' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Страна',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Страна\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
