<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.3.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма test',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U6180' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Сколько сотрудников',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сколько сотрудников\' не может быть пустым.'
			)
		),
		'custom_U6176' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Желаемая дата',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Желаемая дата\' не может быть пустым.'
			)
		),
		'custom_U6172' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Тип машины',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Тип машины\' не может быть пустым.'
			)
		),
		'custom_U6184' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Модель',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Модель\' не может быть пустым.'
			)
		),
		'custom_U6390' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Серийный номер',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Серийный номер\' не может быть пустым.'
			)
		),
		'custom_U6402' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Год и месяц выпуска',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Год и месяц выпуска\' не может быть пустым.'
			)
		),
		'custom_U6414' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Сортируемые продукты',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сортируемые продукты\' не может быть пустым.'
			)
		),
		'custom_U6426' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Дополнительная информация',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Дополнительная информация\' не может быть пустым.'
			)
		),
		'custom_U6313' => array(
			'order' => 2,
			'type' => 'radiogroup',
			'label' => 'Место обучения',
			'required' => true,
			'optionItems' => array(
				'На площадке СиСорт',
				'На моей площадке (обучение с выездом к заказчику)'
			),
			'errors' => array(
				'required' => 'Поле \'Место обучения\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Место обучения\".'
			)
		)
	)
);

process_form($form);
?>
