<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.3.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма test',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U5467' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Качественные показатели исходного продукта',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Качественные показатели исходного продукта\' не может быть пустым.'
			)
		),
		'custom_U5437' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Качественные показатели годного',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Качественные показатели годного\' не может быть пустым.'
			)
		),
		'custom_U5428' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Качественные показатели отхода',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Качественные показатели отхода\' не может быть пустым.'
			)
		),
		'custom_U5488' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Требуемая производительность',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Требуемая производительность\' не может быть пустым.'
			)
		),
		'custom_U5458' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Описание продукта сортировки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Описание продукта сортировки\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
